<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Role extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Role_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'role/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'role/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'role/index.html';
            $config['first_url'] = base_url() . 'role/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Role_model->total_rows($q);
        $role = $this->Role_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'role_data' => $role,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('role/role_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Role_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_role' => $row->id_role,
		'job' => $row->job,
		'keterangan' => $row->keterangan,
	    );
            $this->load->view('role/role_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('role'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('role/create_action'),
	    'id_role' => set_value('id_role'),
	    'job' => set_value('job'),
	    'keterangan' => set_value('keterangan'),
	);
        $this->load->view('role/role_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'job' => $this->input->post('job',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Role_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('role'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Role_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('role/update_action'),
		'id_role' => set_value('id_role', $row->id_role),
		'job' => set_value('job', $row->job),
		'keterangan' => set_value('keterangan', $row->keterangan),
	    );
            $this->load->view('role/role_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('role'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_role', TRUE));
        } else {
            $data = array(
		'job' => $this->input->post('job',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Role_model->update($this->input->post('id_role', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('role'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Role_model->get_by_id($id);

        if ($row) {
            $this->Role_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('role'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('role'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('job', 'job', 'trim|required');
	$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');

	$this->form_validation->set_rules('id_role', 'id_role', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Role.php */
/* Location: ./application/controllers/Role.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-22 15:51:05 */
/* http://harviacode.com */